spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
logging:
  level:
    org.springframework.data: debug
