spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpademo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

logging:
  level:
    org.springframework.data: debug
    org.springframework.orm: debug
    org.mybatis: debug
    root: info
mybatis-plus:
  mapper-locations: UserMapper.xml
